name: CI-SPLaSK-assessment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel!
jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        id: Initialize-step
        env: 
          access-token: ${{secrets.ENOVADE_TOKEN}}
        run: echo "Initialize SPLaSK service!"
        
  scan-website:
    runs-on: ubuntu-latest
    needs: initialize
    steps:
      - name: Send request to scan website
        id: scan-step
        uses: Enovade/splask@v1.0.1
        with:
          splaskurl: ${{secrets.ENOVADE_TOKEN}}
          url: 'https://www.mampu.gov.my/'
          scope: 'all'
          
      - name: Save result to file 
        run: echo ${{toJson(steps.scan-step.outputs.jawapan)}} > jawapan.json
        
      - name: JSON-to-HTML
        id: json-html
        uses: Enovade/json2html@v0.2.1
        with:
          json: ${{steps.scan-step.outputs.jawapan}}
      
      - name: Save result to html 
        run: |
          echo '"' >> htmloutput.html
          cat htmloutput.html 
          echo ${steps.scan-step.json-html.htmloutput} >> htmloutput.html 
          cat htmloutput.html 
          echo '"' >> htmloutput.html
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: htmloutput.html
          if-no-files-found: error
          
  artifact:
      runs-on: ubuntu-latest
      needs: scan-website
      steps:
        - name: Run a one-line script
          run: echo "Artifact successfully created!"
